# HTTP 连接配置 T0D0
ok:
  http:
    connect-timeout: 30
    keep-alive-duration: 300
    max-idle-connections: 200
    read-timeout: 30
    write-timeout: 30


# 数据库相关的信息配置 TODO
spring:
  datasource:
    url:
    username:
    password:
    driver-class-name:
  # kafka相关的信息配置 TODO
  kafka:
    bootstrap-servers:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto:
        offset:
          reset: earliest
      auto-commit-interval: 1000
      enable-auto-commit: true
  # redis 相关配置 TODO
  redis:
    host:
    port:
    password:


# 消息topicName TODO
austin:
  topic:
    name: austinTopic
  # GrayLog ip 地址 TODO
  grayLogIp:

# 监控配置  TODO
management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true

# apollo  TODO
app:
  id: austin
apollo:
  bootstrap:
    enabled: true
    namespaces: boss.austin

# xxl job TODO
xxl:
  job:
    admin:
      addresses:  # 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      username:  # 后台用户名
      password:  # 后台密码
    executor:
      appname: austin # 执行器 AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      ip: # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      port: 6666 # ### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      logpath:  # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logretentiondays: 30 # 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
    accessToken:  # 执行器通讯TOKEN [选填]：非空时启用；
# tomcat / HikariPool(数据库连接池 配置） TODO